/* tslint:disable */
/* eslint-disable */
/**
 * POW Cards API
 * API for creating and managing POW wallet cards with Solana authentication
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@passentry.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckApiHealth200Response
 */
export interface CheckApiHealth200Response {
    /**
     * 
     * @type {string}
     * @memberof CheckApiHealth200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the CheckApiHealth200Response interface.
 */
export function instanceOfCheckApiHealth200Response(value: object): value is CheckApiHealth200Response {
    return true;
}

export function CheckApiHealth200ResponseFromJSON(json: any): CheckApiHealth200Response {
    return CheckApiHealth200ResponseFromJSONTyped(json, false);
}

export function CheckApiHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckApiHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CheckApiHealth200ResponseToJSON(json: any): CheckApiHealth200Response {
    return CheckApiHealth200ResponseToJSONTyped(json, false);
}

export function CheckApiHealth200ResponseToJSONTyped(value?: CheckApiHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

