/* tslint:disable */
/* eslint-disable */
/**
 * POW Cards API
 * API for creating and managing POW wallet cards with Solana authentication
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@passentry.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InitializeClaimProcess200Response
 */
export interface InitializeClaimProcess200Response {
    /**
     * 
     * @type {string}
     * @memberof InitializeClaimProcess200Response
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof InitializeClaimProcess200Response
     */
    nonce?: string;
    /**
     * 
     * @type {Date}
     * @memberof InitializeClaimProcess200Response
     */
    issuedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof InitializeClaimProcess200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the InitializeClaimProcess200Response interface.
 */
export function instanceOfInitializeClaimProcess200Response(value: object): value is InitializeClaimProcess200Response {
    return true;
}

export function InitializeClaimProcess200ResponseFromJSON(json: any): InitializeClaimProcess200Response {
    return InitializeClaimProcess200ResponseFromJSONTyped(json, false);
}

export function InitializeClaimProcess200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitializeClaimProcess200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : json['domain'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'issuedAt': json['issuedAt'] == null ? undefined : (new Date(json['issuedAt'])),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InitializeClaimProcess200ResponseToJSON(json: any): InitializeClaimProcess200Response {
    return InitializeClaimProcess200ResponseToJSONTyped(json, false);
}

export function InitializeClaimProcess200ResponseToJSONTyped(value?: InitializeClaimProcess200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': value['domain'],
        'nonce': value['nonce'],
        'issuedAt': value['issuedAt'] == null ? undefined : ((value['issuedAt']).toISOString()),
        'message': value['message'],
    };
}

