/* tslint:disable */
/* eslint-disable */
/**
 * POW Cards API
 * API for creating and managing POW wallet cards with Solana authentication
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@passentry.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InitializeClaimProcess429Response
 */
export interface InitializeClaimProcess429Response {
    /**
     * 
     * @type {string}
     * @memberof InitializeClaimProcess429Response
     */
    error?: string;
}

/**
 * Check if a given object implements the InitializeClaimProcess429Response interface.
 */
export function instanceOfInitializeClaimProcess429Response(value: object): value is InitializeClaimProcess429Response {
    return true;
}

export function InitializeClaimProcess429ResponseFromJSON(json: any): InitializeClaimProcess429Response {
    return InitializeClaimProcess429ResponseFromJSONTyped(json, false);
}

export function InitializeClaimProcess429ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitializeClaimProcess429Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function InitializeClaimProcess429ResponseToJSON(json: any): InitializeClaimProcess429Response {
    return InitializeClaimProcess429ResponseToJSONTyped(json, false);
}

export function InitializeClaimProcess429ResponseToJSONTyped(value?: InitializeClaimProcess429Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

