/* tslint:disable */
/* eslint-disable */
/**
 * POW Cards API
 * API for creating and managing POW wallet cards with Solana authentication
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@passentry.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifySignatureAndCreatePass200Response
 */
export interface VerifySignatureAndCreatePass200Response {
    /**
     * 
     * @type {string}
     * @memberof VerifySignatureAndCreatePass200Response
     */
    downloadUrl?: string;
}

/**
 * Check if a given object implements the VerifySignatureAndCreatePass200Response interface.
 */
export function instanceOfVerifySignatureAndCreatePass200Response(value: object): value is VerifySignatureAndCreatePass200Response {
    return true;
}

export function VerifySignatureAndCreatePass200ResponseFromJSON(json: any): VerifySignatureAndCreatePass200Response {
    return VerifySignatureAndCreatePass200ResponseFromJSONTyped(json, false);
}

export function VerifySignatureAndCreatePass200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifySignatureAndCreatePass200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
    };
}

export function VerifySignatureAndCreatePass200ResponseToJSON(json: any): VerifySignatureAndCreatePass200Response {
    return VerifySignatureAndCreatePass200ResponseToJSONTyped(json, false);
}

export function VerifySignatureAndCreatePass200ResponseToJSONTyped(value?: VerifySignatureAndCreatePass200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downloadUrl': value['downloadUrl'],
    };
}

